/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * 模板类型枚举
*/
export const enum TemplateType {
  Pages = 0,
  Components = 1,
  Project = 2
}
export function sum(a: number, b: number): number
/**
 * 初始化本地yaml配置文件
*/
export function initYamlFile(): void
/**
 * 根据用户输入生成yaml配置文件
*/
export function initYamlFileWithStdin(): void
/**
 * 请求模板
*/
export function requestRemoteTemplates(templateType: TemplateType): Promise<void>
